apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-secret
  namespace: git
spec:
  secretName: gitea-secret
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
  commonName: git.k8s.com
  dnsNames:
  - git.k8s.com
