---
###################################################
# Persistence Volume Claim
###################################################
kind: PersistentVolume
apiVersion: v1
metadata:
  name: git-pv
  namespace: gitea-repo
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: gitea-repo
    name: git-pvc
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: git-data
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pvc
  namespace: gitea-repo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # Ensure this matches the Longhorn StorageClass in your cluster
  resources:
    requests:
      storage: 5Gi
