###############################
# Service
###############################
---
kind: Service
apiVersion: v1
metadata:
  name: gitea-service
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-http
    port: 80
    targetPort: 3000
  - name: gitea-ssh
    port: 22
    targetPort: 22
---
###################################################
# Ingress
###################################################
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gitea
spec:
  virtualhost:
    fqdn: {{ .Values.ingress.host }}
    # Redirect plain HTTP -> HTTPS (equivalent of force-ssl-redirect)
    insecure:
      policy: Redirect
    {{- if .Values.ingress.tls.enabled }}
    tls:
      secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
  routes:
    - conditions:
        - prefix: /
      # Per-route timeouts approximating your NGINX read/send/connect timeouts
      timeoutPolicy:
        # How long Envoy will wait for the upstream to respond
        response: 3600s
        # Idle timeout for the connection (no data in either direction)
        idle: 3600s
      services:
        - name: gitea-service
          port: 80