---
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: gitea-repo
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-http
    port: 3000
  - name: gitea-ssh
    port: 22

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-tls
  namespace: gitea-repo
  annotations:
    {{- toYaml .Values.ingress.annotations | indent 4 }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: tls-gitea
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea-service
            port:
              number: 3000
