apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
spec:
  secretName: gitea # <-- cert-manager will create/update this secret
  dnsNames:
    - git.k8s.com
  issuerRef:
    name: {{ .Values.issuerRef.name }} # your ClusterIssuer
    kind: {{ .Values.issuerRef.kind }}
  usages:
    - digital signature
    - key encipherment